"use client";
import {useMemo,useState} from "react";
import {motion,AnimatePresence} from "framer-motion";
import {ArrowRight,BarChart3,BedDouble,Building2,CalendarDays,Check,ChevronDown,ChevronLeft,ChevronRight,Home,KeyRound,MapPin,Menu,MessageCircle,ParkingCircle,Search,Sparkles,Star,TrendingUp,Users,Wifi,X} from "lucide-react";

const districts=["Tous","Racine","Aïn Diab","Triangle d'Or","Gauthier","Palmier","Anfa"];
const names=["Maison Sillage","L’Atelier Anfa","Suite Majorelle","Le Patio Racine","Horizon Atlantique","Maison Verre","Studio Matisse","Le Belvédère","Appartement Atlas","Nid d’Anfa","Villa Blanche","Casa Nomade","Le Cèdre","Suite Azur","Terrasse 33","Maison Lumière","Le Grand Palmier","Dar Studio"];
const homes=names.map((name,i)=>({id:i+1,name,district:districts[(i%6)+1],guests:2+(i%5),beds:1+(i%3),price:780+(i*95),rating:(4.72+(i%5)*.05).toFixed(2),image:["/images/hero.png","/images/ocean.png","/images/terrace.png"][i%3],parking:i%2===0,terrace:i%3!==0,badge:i%4===0?"Nouveau":i%4===1?"Signature":"Disponible"}));
const services=[
 ["Audit & stratégie","Projection locative, positionnement et plan d’action sur mesure.",BarChart3],
 ["Mise en scène","Ameublement, décoration et photographie éditoriale.",Sparkles],
 ["Exploitation","Calendriers, prix dynamiques, réservations et relation voyageurs.",KeyRound],
 ["Intendance","Accueil, ménage, linge, maintenance et contrôle qualité.",Home],
 ["Pilotage","Reporting transparent, suivi des revenus et recommandations.",TrendingUp],
 ["Investissement","Sourcing, analyse, acquisition et mise en exploitation.",Building2]
];
const faqs=[
 ["Propriétaire","Comment estimez-vous le potentiel de mon bien ?","Nous croisons le quartier, la typologie, la saisonnalité et les performances de biens comparables. L’audit aboutit à trois scénarios chiffrés et à une recommandation claire."],
 ["Propriétaire","Puis-je suivre les réservations et les revenus ?","Oui. Vous recevez une synthèse régulière des réservations, revenus, charges et interventions, avec un interlocuteur dédié à Casablanca."],
 ["Investisseur","Studio Capital recherche-t-il le logement ?","Oui. Nous définissons le cahier d’investissement, sourçons les opportunités, analysons la rentabilité, coordonnons les visites puis la mise en exploitation."],
 ["Investisseur","Quel budget faut-il prévoir ?","Le projet est calibré selon votre apport, votre financement et votre objectif. Notre simulateur donne une première lecture avant l’étude personnalisée."],
 ["Voyageur","Comment se déroule l’arrivée ?","Les instructions sont envoyées avant votre arrivée. Selon le logement, l’accueil est autonome ou assuré par notre équipe locale."],
 ["Voyageur","Comment joindre l’assistance ?","Notre assistance voyageurs est disponible par WhatsApp durant le séjour pour toute demande liée au logement."]
];
const steps=["Diagnostic du projet","Audit & projection","Préparation signature","Lancement & diffusion","Optimisation continue"];

function Logo({light=false}:{light?:boolean}){return <a href="#top" className={`brand ${light?"light":""}`} aria-label="Studio Capital accueil"><span className="monogram">SC</span><span><b>STUDIO CAPITAL</b><small>CASABLANCA</small></span></a>}
function Modal({home,onClose}:{home:typeof homes[0]|null,onClose:()=>void}){return <AnimatePresence>{home&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}><motion.article initial={{y:50,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}} onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose} aria-label="Fermer"><X/></button><img src={home.image} alt={home.name}/><div className="modal-copy"><span className="eyebrow">{home.district} · Casablanca</span><h2>{home.name}</h2><div className="features"><span><Users/> {home.guests} voyageurs</span><span><BedDouble/> {home.beds} chambres</span><span><Wifi/> Wi-Fi</span>{home.parking&&<span><ParkingCircle/> Parking</span>}</div><p>Une adresse confidentielle pensée comme une maison privée : volumes lumineux, matières naturelles, literie hôtelière et attention portée à chaque détail.</p><div className="modal-bottom"><div><small>À partir de</small><strong>{home.price.toLocaleString("fr-FR")} MAD <i>/ nuit</i></strong></div><button className="btn gold" onClick={()=>alert("Demande envoyée — notre conciergerie vous répond sous quelques minutes.")}>Demander ce séjour <ArrowRight/></button></div></div></motion.article></motion.div>}</AnimatePresence>}

export default function StudioCapital(){
 const [menu,setMenu]=useState(false),[district,setDistrict]=useState("Tous"),[guests,setGuests]=useState(2),[parking,setParking]=useState(false),[selected,setSelected]=useState<typeof homes[0]|null>(null),[faq,setFaq]=useState(0),[faqQuery,setFaqQuery]=useState(""),[price,setPrice]=useState(1450000),[night,setNight]=useState(1050),[occupancy,setOccupancy]=useState(68),[sent,setSent]=useState(false),[profile,setProfile]=useState("Propriétaire");
 const filtered=useMemo(()=>homes.filter(h=>(district==="Tous"||h.district===district)&&h.guests>=guests&&(!parking||h.parking)),[district,guests,parking]);
 const revenue=Math.round(night*365*occupancy/100),net=Math.round(revenue*.68),yieldNet=(net/price*100).toFixed(1);
 const faqFiltered=faqs.filter(f=>(f.join(" ").toLowerCase().includes(faqQuery.toLowerCase())));
 return <main id="top">
  <header><Logo light/><nav className={menu?"open":""}><a href="#services">Services</a><a href="#method">Méthode</a><a href="#homes">Logements</a><a href="#invest">Investir</a><a href="#faq">FAQ</a><a href="#contact">Contact</a></nav><a className="nav-cta" href="#estimate">Estimer mon bien <ArrowRight/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></header>
  <section className="hero"><img src="/images/hero.png" alt="Appartement Studio Capital à Casablanca"/><div className="veil"/><motion.div className="hero-copy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.9}}><span className="eyebrow pale">CONCIERGERIE · GESTION · INVESTISSEMENT</span><h1>Votre patrimoine,<br/><em>pleinement vivant.</em></h1><p>Nous transformons les plus belles adresses de Casablanca en expériences désirables et en actifs performants.</p><div className="actions"><a className="btn gold" href="#estimate">Estimer mes revenus <ArrowRight/></a><a className="btn ghost" href="#homes">Découvrir nos adresses</a></div></motion.div><div className="hero-proof"><span><b>4,92/5</b><small>Satisfaction voyageurs</small></span><span><b>+31%</b><small>Revenus moyens optimisés</small></span><span><b>24/7</b><small>Assistance locale</small></span></div><a className="scroll" href="#intro">DÉCOUVRIR <i/></a></section>
  <section className="intro section" id="intro"><div><span className="eyebrow">UNE AUTRE IDÉE DE LA GESTION</span><h2>La rigueur d’un investisseur.<br/>Le regard d’un hôtelier.</h2></div><div><p>Studio Capital réunit stratégie immobilière, direction artistique et excellence opérationnelle. Votre bien est suivi comme un actif, présenté comme une adresse et vécu comme une évidence.</p><a className="text-link" href="#method">Notre méthode <ArrowRight/></a></div></section>
  <section className="services section" id="services"><div className="section-head"><span className="eyebrow">EXPERTISE INTÉGRÉE</span><h2>Un seul partenaire.<br/>Chaque détail maîtrisé.</h2></div><div className="service-grid">{services.map(([title,desc,Icon],i)=><motion.article key={String(title)} whileHover={{y:-8}}><span>0{i+1}</span><Icon/><h3>{String(title)}</h3><p>{String(desc)}</p><button onClick={()=>alert(`${title} — un conseiller vous rappelle pour détailler cette expertise.`)}>Explorer <ArrowRight/></button></motion.article>)}</div></section>
  <section className="method" id="method"><div className="method-image"><img src="/images/terrace.png" alt="Terrasse premium à Casablanca"/><span>DE LA CLÉ À LA PERFORMANCE</span></div><div className="method-copy"><span className="eyebrow pale">NOTRE MÉTHODE</span><h2>Simple pour vous.<br/>Précis pour nous.</h2><div className="timeline">{steps.map((s,i)=><div key={s}><b>0{i+1}</b><span><strong>{s}</strong><small>{["Échange, objectifs et qualification du bien.","Visite, données de marché et scénario de revenus.","Aménagement, photographie et standards hôteliers.","Annonces, distribution et expérience voyageurs.","Tarification dynamique, reporting et amélioration."][i]}</small></span></div>)}</div><a className="btn outline-light" href="#contact">Confier mon logement <ArrowRight/></a></div></section>
  <section className="homes section" id="homes"><div className="section-head row"><div><span className="eyebrow">COLLECTION PRIVÉE</span><h2>Des adresses à vivre.</h2></div><p>Une sélection de lieux singuliers, préparés et suivis par notre équipe à Casablanca.</p></div><div className="filters"><label><MapPin/><select value={district} onChange={e=>setDistrict(e.target.value)}>{districts.map(d=><option key={d}>{d}</option>)}</select></label><label><Users/><select value={guests} onChange={e=>setGuests(+e.target.value)}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}+ voyageurs</option>)}</select></label><button className={parking?"active":""} onClick={()=>setParking(!parking)}><ParkingCircle/> Parking</button><span>{filtered.length} adresses</span></div><div className="home-grid">{filtered.slice(0,6).map(h=><motion.article layout key={h.id} onClick={()=>setSelected(h)}><div className="photo"><img src={h.image} alt={h.name}/><span>{h.badge}</span><button aria-label="Voir le logement"><ArrowRight/></button></div><div className="home-info"><span>{h.district} · Casablanca</span><h3>{h.name}</h3><div><small><Users/> {h.guests}</small><small><BedDouble/> {h.beds}</small>{h.terrace&&<small>Terrasse</small>}<b>{h.price.toLocaleString("fr-FR")} MAD <i>/ nuit</i></b></div></div></motion.article>)}</div>{filtered.length===0&&<div className="empty"><Search/><h3>Aucune adresse avec ces critères</h3><button onClick={()=>{setDistrict("Tous");setGuests(1);setParking(false)}}>Réinitialiser la recherche</button></div>}<button className="btn navy" onClick={()=>{setDistrict("Tous");setGuests(1);setParking(false)}}>Voir les 18 logements <ArrowRight/></button></section>
  <section className="numbers"><span><b>48</b><small>adresses sous gestion</small></span><span><b>92%</b><small>taux d’occupation en haute saison</small></span><span><b>7,4 M</b><small>MAD de revenus voyageurs pilotés</small></span><span><b>11 min</b><small>temps de réponse moyen</small></span></section>
  <section className="invest section" id="invest"><div className="invest-intro"><span className="eyebrow">INVESTIR À CASABLANCA</span><h2>De l’intuition<br/>à la décision.</h2><p>Visualisez le potentiel de votre projet. Notre équipe affine ensuite chaque hypothèse avec les données du quartier et la réalité opérationnelle.</p><div className="mini-quote"><TrendingUp/><span><b>Un investissement se choisit.</b><small>Une performance se construit.</small></span></div></div><div className="calculator"><h3>Votre première projection</h3><label><span>Prix d’acquisition <b>{price.toLocaleString("fr-FR")} MAD</b></span><input type="range" min="700000" max="3500000" step="50000" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label><span>Prix moyen / nuit <b>{night} MAD</b></span><input type="range" min="550" max="2200" step="50" value={night} onChange={e=>setNight(+e.target.value)}/></label><label><span>Taux d’occupation <b>{occupancy}%</b></span><input type="range" min="35" max="92" value={occupancy} onChange={e=>setOccupancy(+e.target.value)}/></label><div className="results"><span><small>Revenus bruts annuels</small><b>{revenue.toLocaleString("fr-FR")} MAD</b></span><span><small>Revenus nets estimés</small><b>{net.toLocaleString("fr-FR")} MAD</b></span><span className="highlight"><small>Rendement net estimé</small><b>{yieldNet}%</b></span></div><p className="disclaimer">Simulation indicative, hors financement et fiscalité. Les résultats ne constituent pas une garantie de rendement.</p><a href="#contact" className="btn gold">Étudier mon projet <ArrowRight/></a></div></section>
  <section className="testimonial"><span className="eyebrow pale">LA CONFIANCE SE MESURE</span><div className="stars">★★★★★</div><blockquote>“À distance, je voulais de la visibilité sans gérer le quotidien. Studio Capital a repositionné l’appartement, augmenté le revenu et surtout installé une vraie sérénité.”</blockquote><p><b>Yasmine B.</b> · Propriétaire MRE, Paris / Casablanca</p><div className="pager"><button><ChevronLeft/></button><span>01 / 05</span><button><ChevronRight/></button></div></section>
  <section className="faq section" id="faq"><div className="faq-side"><span className="eyebrow">QUESTIONS FRÉQUENTES</span><h2>Avant de nous confier les clés.</h2><div className="faq-search"><Search/><input value={faqQuery} onChange={e=>setFaqQuery(e.target.value)} placeholder="Rechercher une question"/></div></div><div className="accordion">{faqFiltered.map((f,i)=><article key={f[1]} className={faq===i?"open":""}><button onClick={()=>setFaq(faq===i?-1:i)}><span><small>{f[0]}</small>{f[1]}</span><ChevronDown/></button>{faq===i&&<motion.p initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}}>{f[2]}</motion.p>}</article>)}</div></section>
  <section className="estimate" id="estimate"><div><span className="eyebrow pale">PREMIER ÉCHANGE, SANS ENGAGEMENT</span><h2>Quel projet<br/>vous amène ?</h2><p>Quelques informations suffisent pour préparer une première recommandation personnalisée.</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="profiles">{["Propriétaire","Investisseur","Voyageur"].map(p=><button type="button" key={p} className={profile===p?"active":""} onClick={()=>setProfile(p)}>{profile===p&&<Check/>}{p}</button>)}</div>{!sent?<><div className="fields"><label>Nom complet<input required placeholder="Votre nom"/></label><label>Téléphone<input required placeholder="+212 6..."/></label><label>E-mail<input required type="email" placeholder="vous@exemple.com"/></label><label>{profile==="Voyageur"?"Dates souhaitées":profile==="Investisseur"?"Budget du projet":"Quartier du bien"}<input required placeholder={profile==="Voyageur"?"Arrivée — Départ":profile==="Investisseur"?"Ex. 1 500 000 MAD":"Ex. Racine"}/></label></div><button className="btn gold" type="submit">{profile==="Propriétaire"?"Recevoir mon estimation":profile==="Investisseur"?"Être accompagné":"Trouver mon séjour"} <ArrowRight/></button><small>Vos informations restent confidentielles. Aucune donnée n’est enregistrée dans cette démonstration.</small></>:<motion.div className="success" initial={{scale:.95,opacity:0}} animate={{scale:1,opacity:1}}><Check/><h3>Votre demande est bien partie.</h3><p>Un conseiller Studio Capital vous recontactera très prochainement.</p><button type="button" onClick={()=>setSent(false)}>Nouvelle demande</button></motion.div>}</form></section>
  <section className="journal section"><div className="section-head row"><div><span className="eyebrow">LE JOURNAL</span><h2>Regards sur Casablanca.</h2></div><a className="text-link" href="#">Tous les articles <ArrowRight/></a></div><div className="articles">{[["/images/ocean.png","INVESTIR · 8 MIN","Aïn Diab : comprendre le marché locatif en 2026"],["/images/terrace.png","DESIGN · 6 MIN","Les détails qui font choisir un appartement"],["/images/hero.png","GESTION · 5 MIN","Tarification dynamique : au-delà du prix par nuit"]].map(a=><article key={a[2]}><img src={a[0]} alt=""/><small>{a[1]}</small><h3>{a[2]}</h3><a href="#">Lire l’analyse <ArrowRight/></a></article>)}</div></section>
  <footer id="contact"><div className="footer-top"><Logo light/><h2>Faisons de votre prochain bien<br/><em>une adresse qui compte.</em></h2><a className="btn gold" href="#estimate">Parler à un conseiller <ArrowRight/></a></div><div className="footer-grid"><div><small>CASABLANCA</small><p>Triangle d’Or<br/>Casablanca, Maroc</p></div><div><small>CONTACT</small><p>+212 5 20 00 00 00<br/>bonjour@studiocapital.ma</p></div><div><small>EXPLORER</small><a href="#services">Services</a><a href="#homes">Logements</a><a href="#invest">Investissement</a></div><div><small>LA LETTRE STUDIO</small><form onSubmit={e=>{e.preventDefault();alert("Inscription confirmée. Bienvenue dans la lettre Studio Capital.")}}><input type="email" required placeholder="Votre adresse e-mail"/><button aria-label="S’inscrire"><ArrowRight/></button></form></div></div><div className="legal"><span>© 2026 Studio Capital</span><a href="#">Mentions légales</a><a href="#">Confidentialité</a><a href="#">Cookies</a><span>FR · MA</span></div></footer>
  <a className="whatsapp" href="https://wa.me/212600000000?text=Bonjour%20Studio%20Capital" target="_blank" rel="noreferrer" aria-label="Contacter Studio Capital sur WhatsApp"><MessageCircle/><span>Parler à l’équipe</span></a>
  <Modal home={selected} onClose={()=>setSelected(null)}/>
 </main>
}
